### PR TITLE
Displaying numbers repeatedly

### PR DESCRIPTION
**Pull request by onenoc**
Hi TJ,

I added a condition to check to see if we've already printed a number on the y-axis, and if so, not to print it again.

Regards,
Alex

### CODE REVIEW

**Comment by tj** [comment]
hmmm I think ideally we compare the ranges and display them with event spacing

**Comment by tj** [comment]
im not a huge fan of how i wrote it currently, the uneven jumps from 67 - 55 etc bugs me hahaha

**Comment by onenoc** [comment]
I'll look into if I can do something about it, and if I have hard time/get too busy I"ll let you know.

**Comment by tj** [comment]
sounds good!

**Comment by onenoc** [comment]
Wasn't able to look at it for a couple days, but I noticed that in small.txt, it gives 2 bars for 1, 5 bars for 2, and 7 bars for 3.  I'll try fixing that.

**Pull request merged**
